config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'tags/index'
    get 'tags/edit'
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root to: "homes#top"
    get "homes/about"=>"homes#about", as: "about"
    
    resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
    end
    
    get "users/mypage/:id" => "users#show", as: "users_mypage"
    get "users/information/edit" => "users#edit"
    patch "users/information" => "users#update"
    get "/users/check" => "users#check"
    patch "/users/withdraw" => "users#withdraw"
    
    resources :users do
      member do
        get :likes
      end
    end
    get "search" => "posts#search"
  end
  
  namespace :admin do
    get "/" => "homes#top"
    
    resources :genres, only: [:index, :create, :edit, :update,]
    resources :genres do
      member do
        delete :destroy
      end
    end
    
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
     resources :comments, only: [:create, :destroy]
    
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
  end
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/association_post_and_tag.rb
class AssociationPostAndTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :name, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  belongs_to :genre
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :spot_image
  
  has_many :association_post_and_tags, dependent: :destroy
  has_many :tags, through: :association_post_and_tags
  
  validates :name, presence: true
  validates :explanation, length: { minimum: 1, maximum: 100 }, presence: true
    
  def get_spot_image
    (spot_image.attached?) ? spot_image : 'no_spot_image.jpg'
  end
  
  def liked_by?(user)
   likes.exists?(user_id: user.id)
  end
  
  def self.search(keyword)
    where("name LIKE ?", "%#{keyword}%")
  end
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :association_post_and_tags, dependent: :destroy
  has_many :posts, through: :association_post_and_tags

  validates :tag_type, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,
    length: { maximum: 50 }
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def active_for_authentication?
    super && (is_withdrawal == false)
  end
  
  def user_status
    if is_withdrawal == true
      "退会"
    else
      "有効"
    end
  end
  
GUEST_USER_EMAIL = "guest@example.com"
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
     redirect_back(fallback_location: root_path)
    else
     @genre = Genre.new
     @genres = Genre.all
     render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path, notice: "ジャンルを削除しました。"
  end
  
  
  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to admin_post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end
  
  def post_params
    params.require(:post).permit(:name, :explanation, :address, :spot_image, :genre_id, tag_ids: [])
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @tag = Tag.new
    @tags = Tag.page(params[:page])
  end
  
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path, notice: "新しいタグを追加しました。"
    else
      @tags = Tag.page(params[:page])
      flash.now[:alert] = "タグの追加に失敗しました。"
      render :index
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end
  
  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path, notice: "タグの更新に成功しました。"
    else
      flash.now[:alert] = "タグの更新に失敗しました。"
      render :edit
    end
  end
  
  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admin_tags_path, notice: "タグを削除しました。"
  end
  
  
  private
  
  def tag_params
    params.require(:tag).permit(:tag_type, tag_ids: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/genres/edit.html.erb
<div class="container border border-white contents-area bg-white" >
  <div class="row mt-4 md-2">
    <div class="col-md-6 mx-auto">

      <h3><strong class="border-bottom border-dark">ジャンル編集</strong></h3>

        <%= form_with model: @genre, url:admin_genre_path,method: :patch do |f| %>
          <table class="table table-borderless mt-3">
            <tbody>
              <tr>
                <td class="align-middle">
                  <label for="genre_name">ジャンル名</label>
                </td>
                <td class="align-middle">
                  <%= f.text_field:name %>
                </td>
                <td>
                  <%= f.submit "変更を保存",class:"btn btn-success" %>
                </td>
              </tr>
            </tbody>
          </table>
        <% end %>

    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container border border-white contents-area bg-white">
 <div class="row mt-5 mb-5">
  <div class="col-xl-10 col-lg-10 col-md-12 col-sm-12 mx-auto">
   
  <h3 class="text-center"><strong class="">ジャンル一覧・追加/削除</strong></h3>

        <%= form_with model: @genre, url: admin_genres_path, local:true do |f| %>
        <table class="table table-border contents-area mt-5">
         <tr>
          <td class="align-middle">タグ名</td>
          <td class="center align-middle">
            <%= f.text_field:name,:size=>"35" %>
          </td>
          <td colspan="2"></td>
          <td>
             <%= f.submit "新規登録", class: "btn btn-primary btn-lg" %>
          </td>
         </tr>
          <% end %>
         <thead class="table-active">
            <tr>
              <th>ジャンル</th>
              <th colspan="6"></th>
            </tr>
          </thead>
          
          <tbody>
              <% @genres.each do |genre| %>
                <tr>
                  <td class="align-middle"><%= genre.name %></td>
                  <td colspan="3"></td>
                  <td>
                    <%= link_to "ジャンルを変更する", edit_admin_genre_path(genre.id), class: "btn btn-success" %>
                    <%= link_to "ジャンルを削除する", admin_genre_path(genre.id), class: "btn btn-danger", method: :delete, "data-confirm" => "本当にジャンルを削除しますか?" %>
                  </td>
                </tr>
              <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>