config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'tags/index'
    get 'tags/edit'
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root to: "homes#top"
    get "homes/about"=>"homes#about", as: "about"
    
    resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
    end
    
    get "users/mypage/:id" => "users#show", as: "users_mypage"
    get "users/information/edit" => "users#edit"
    patch "users/information" => "users#update"
    get "/users/check" => "users#check"
    patch "/users/withdraw" => "users#withdraw"
    
    resources :users do
      member do
        get :likes
      end
    end
    get "search" => "posts#search"
  end
  
  namespace :admin do
    get "/" => "homes#top"
    
    resources :genres, only: [:index, :create, :edit, :update,]
    resources :genres do
      member do
        delete :destroy
      end
    end
    
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
     resources :comments, only: [:create, :destroy]
    
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
  end
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/association_post_and_tag.rb
class AssociationPostAndTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :name, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  belongs_to :genre
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :spot_image
  
  has_many :association_post_and_tags, dependent: :destroy
  has_many :tags, through: :association_post_and_tags
  
  validates :name, presence: true
  validates :explanation, length: { minimum: 1, maximum: 100 }, presence: true
    
  def get_spot_image
    (spot_image.attached?) ? spot_image : 'no_spot_image.jpg'
  end
  
  def liked_by?(user)
   likes.exists?(user_id: user.id)
  end
  
  def self.search(keyword)
    where("name LIKE ?", "%#{keyword}%")
  end
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :association_post_and_tags, dependent: :destroy
  has_many :posts, through: :association_post_and_tags

  validates :tag_type, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,
    length: { maximum: 50 }
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def active_for_authentication?
    super && (is_withdrawal == false)
  end
  
  def user_status
    if is_withdrawal == true
      "退会"
    else
      "有効"
    end
  end
  
GUEST_USER_EMAIL = "guest@example.com"
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @tag = Tag.new
    @tags = Tag.page(params[:page])
  end
  
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path, notice: "新しいタグを追加しました。"
    else
      @tags = Tag.page(params[:page])
      flash.now[:alert] = "タグの追加に失敗しました。"
      render :index
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end
  
  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path, notice: "タグの更新に成功しました。"
    else
      flash.now[:alert] = "タグの更新に失敗しました。"
      render :edit
    end
  end
  
  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admin_tags_path, notice: "タグを削除しました。"
  end
  
  
  private
  
  def tag_params
    params.require(:tag).permit(:tag_type, tag_ids: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
 <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #2e8b57;">

  <a class="navbar-brand" href="/"><%= image_tag asset_path('logo.jpg'), size: "50x50" %></a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
   </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

          <li class="ml-1 pl-5">
            <%= link_to  users_mypage_path(current_user),class: 'nav-link text-light' do %> マイページ
            <% end %>
          </li>
          <li class="ml-1">
            <%=  link_to posts_path,class: 'nav-link text-light' do %> 投稿一覧
            <% end %>
          </li>
          <li class="ml-1">
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %> ログアウト
            <% end %>
          </li>

      <% elsif admin_signed_in? %>

          <li class="ml-1">
            <%=  link_to admin_posts_path ,class: 'nav-link text-light' do %> 投稿一覧
            <% end %>
          </li>
          <li class="ml-1">
            <%=  link_to admin_users_path ,class: 'nav-link text-light' do %> 会員一覧
            <% end %>
          </li>
          <li class="ml-1">
            <%=  link_to admin_genres_path ,class: 'nav-link text-light' do %> ジャンル一覧
            <% end %>
          </li>
          <li class="ml-1">
            <%=  link_to admin_tags_path ,class: 'nav-link text-light' do %> タグ一覧
            <% end %>
          </li>
          <li class="ml-1">
            <%=  link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-light' do %> ログアウト
            <% end %>
          </li>

      <% else %>

          <li class="ml-1">
            <%= link_to about_path,class: 'nav-link text-light' do %> About
            <% end %>
          </li>
          <li class="ml-1">
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %> 新規登録
            <% end %>
          </li>
          <li class="ml-1">
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %> ログイン
            <% end %>
          </li>

      <% end %>
      </ul>
    </div>
 </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>N.P.Search</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/93c66f0f8c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #c8fac8;">
    <%= render 'layouts/header' %>
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>